### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gabriel-maxx** [Fyyre/oldsite#1]
Hello, could you help me how do I disable requirement of driver signing in winload.exe using ida? in the bootloader.txt file you just teach how to disable PatchGuard...

**Comment by Fyyre** [comment]
Hello - I recommend you see this project: https://github.com/Mattiwatti/EfiGuard/tree/master
I no longer have the time to continue to make PatchGuard kills. Also today, there are many available. When I originally wrote bootloader.txt, it was one of the first three methods discovered.

**Comment by gabriel-maxx** [comment]
> Hello - I recommend you see this project: https://github.com/Mattiwatti/EfiGuard/tree/master
> I no longer have the time to continue to make PatchGuard kills. Also today, there are many available. When I originally wrote bootloader.txt, it was one of the first three methods discovered.

Ok thanks
